### ISSUE TITLE
Error: spawn sass ENOENT

### ISSUE THREAD

**Issue by jyasskin** [google/web-starter-kit#659]
After downloading https://api.github.com/repos/google/web-starter-kit/zipball/v0.5.2 and running `npm install` in the resulting directory, `gulp serve:dist` produces:

```
$ gulp serve:dist
[20:39:22] Using gulpfile ~/tmp/google-web-starter-kit-489a6ab/gulpfile.js
[20:39:22] Starting 'clean'...
[20:39:22] Finished 'clean' after 8.35 ms
[20:39:22] Starting 'default'...
[20:39:22] Starting 'styles'...
{ [Error: spawn sass ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn sass',
  path: 'sass',
  spawnargs: 
   [ '--style',
     'expanded',
     '--precision',
     '10',
     '--update',
     '/tmp/gulp-ruby-sass:/tmp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9',
     '--load-path',
     'app/styles',
     '--load-path',
     'app/styles/components' ],
  name: 'Error',
  message: 'spawn sass ENOENT',
  stack: 'Error: spawn sass ENOENT\n    at exports._errnoException (util.js:734:11)\n    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)\n    at child_process.js:1114:20\n    at process._tickCallback (node.js:349:13)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass' }
[20:39:23] 'styles' all files 0 B
[20:39:23] Finished 'styles' after 964 ms
[20:39:23] Starting 'jshint'...
...
```

Is there a step missing in https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up?

**Comment by addyosmani** [comment]
The docs site currently needs an update to reflect we no longer require Ruby to use the kit. Can you try downloading https://github.com/google/web-starter-kit/archive/v0.5.3.zip, running `npm install` and let us know if you still run into the above issues?

**Comment by addyosmani** [comment]
@PaulKinlan You mentioned that https://developers.google.com/web/starter-kit/ is now auto-updating to use the latest version (but I may be wrong on that). It currently still points to the older 0.5.2 version rather than 0.5.3. Anything you can do to help with that?

**Comment by PaulKinlan** [comment]
Its in the build step.... Apparently. Mat can look at this .

**Comment by addyosmani** [comment]
cc @wibblymat :)

**Comment by wibblymat** [comment]
@addyosmani Web Fundamentals checks the version of WSK using https://github.com/jbnicolai/latest-release. This looks at **releases**, and checking WSK I see that 0.5.3 is tagged but the latest actual release is 0.5.2.

**Comment by addyosmani** [comment]
@wibblymat ah, that makes sense. I've just published a new release for 0.5.3 (based on my understanding of how latest-release works). Would https://github.com/google/web-starter-kit/releases/tag/v0.5.3 pull in the correct version now?

**Comment by jyasskin** [comment]
After switching to 0.5.3 (which still isn't the advertised version on https://developers.google.com/web/starter-kit/), I get:

```
$ gulp serve:dist
[09:33:44] Using gulpfile ~/tmp/web-starter-kit-0.5.3/gulpfile.js
[09:33:44] Starting 'clean'...
[09:33:44] Finished 'clean' after 9.66 ms
[09:33:44] Starting 'default'...
[09:33:44] Starting 'styles'...
[09:33:44] 'styles' errored after 103 ms
[09:33:44] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:444:26)
[09:33:44] 'default' errored after 105 ms
[09:33:44] Error: [object Object]
    at formatError (/home/jyasskin/opt/iojs/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/jyasskin/opt/iojs/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:166:7)
    at Gulp.Orchestrator._emitTaskDone (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/run-sequence/index.js:55:4)
```

`npm install node-sass` prints:

```
$ npm install node-sass
-
> node-sass@3.0.0-alpha.0 install /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/node-sass/vendor/linux-x64-43/binding.node

> node-sass@3.0.0-alpha.0 postinstall /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/node-sass
> node scripts/build.js

` /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/node-sass/vendor/linux-x64-43/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.0.0-alpha.0 node_modules/node-sass
├── get-stdin@4.0.1
├── nan@1.7.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, semver@4.3.1, config-chain@1.1.8)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, form-data@0.2.0, mime-types@2.0.10, combined-stream@0.0.7, bl@0.9.4, tough-cookie@0.12.1, http-signature@0.10.1, hawk@2.3.1)
├── sass-graph@1.1.0 (lodash@2.4.1, commander@2.7.1, glob@4.5.3)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, rimraf@2.2.8, graceful-fs@3.0.6, nopt@3.0.1, semver@4.2.2, fstream@1.0.4, glob@4.3.5, tar@1.0.3, minimatch@2.0.4, request@2.51.0, npmlog@1.0.0)
```

Which doesn't look obviously broken. I haven't run any steps in my OS (ubuntu) to install libsass, since I don't see any instructions to do so.

**Comment by PaulKinlan** [comment]
We need a push to devsite which we can do on monday.

**Comment by addyosmani** [comment]
@jyasskin Sorry for the dependency issues you're been running into. Can you try this?

```sh
npm install sass/node-sass#v3.0.0-alpha.1 --save-dev
```

and try again? It unfortunately looks like there were some build issues around Ubuntu in the last version of node-sass and they're trying to get out a release that addresses it.

**Comment by jyasskin** [comment]
I had been using IO.js. Switching back from IO.js 1.5.1 to node.js 0.12.0 fixed the problem with sass (but left me with the problem in #649).

I also tried starting from scratch with IO.js. When it installs node-sass under gulp-sass for the first time, it prints the error:

```
> node-sass@2.0.1 install /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.5/binding.node

> node-sass@2.0.1 postinstall /home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/home/jyasskin/tmp/web-starter-kit-0.5.3/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:865:3
Build failed
```
but otherwise appears to return successfully.

Then I cd'ed into `node_modules/gulp-sass` and ran `npm install sass/node-sass#v3.0.0-alpha.1 --save-dev`, which didn't print any errors. However, then `gulp serve:dist` from the root web-starter-kit directory says:

```
$ gulp serve:dist
[15:25:23] Using gulpfile ~/tmp/web-starter-kit-0.5.3/gulpfile.js
[15:25:23] Starting 'clean'...
[15:25:23] Finished 'clean' after 7.83 ms
[15:25:23] Starting 'default'...
[15:25:23] Starting 'styles'...
```
and quits, with no server but a successful error code.

**Comment by garyterry** [comment]
I still get error #649 when using the latest webkit-0.5.3. I installed dependencies without issue... so no errors with node-sass for me... gulp serve - works fine... but gulp alone still throws:

 ~/dev.server/wsk-0.5.3 $ gulp
[14:38:34] Using gulpfile ~/dev.server/wsk-0.5.3/gulpfile.js
[14:38:34] Starting 'clean'...
[14:38:34] Finished 'clean' after 11 ms
[14:38:34] Starting 'default'...
[14:38:34] Starting 'styles'...
[14:38:39] 'styles' all files 93.17 kB
[14:38:39] Finished 'styles' after 5.28 s
[14:38:39] Starting 'jshint'...
[14:38:42] Starting 'html'...
[14:38:45] Starting 'images'...
[14:38:47] Starting 'fonts'...
[14:38:47] Starting 'copy'...
[14:38:47] Finished 'jshint' after 8.3 s

events.js:85
      throw er; // Unhandled 'error' event
            ^
RangeError: Maximum call stack size exceeded

I get the same error when using- gulp serve:dist

**Comment by nockgeneer** [comment]
gulp-sass error still there on 5.4 as well (at least on Windows), which is marked as latest. The problem goes away after downloading 6.0-r1, so I think it might be fixed. The 'latest release' tag just needs to be moved.

**Comment by addyosmani** [comment]
The very latest RC addresses this issue and we're planning on tagging a final version either this week or next. Closing as fixed (since I can't reproduce these issues on Windows or Mac).
